.PHONY: all
all:
	make -C tclunixsocket
	make -C tcltaglib

.PHONY: clean
clean:
	make -C tclunixsocket clean
	make -C tcltaglib clean

.PHONY: install
install:
	make -C tclunixsocket install
	make -C tcltaglib install

