.PHONY: all
all:
	make -C unixsocket
	make -C taglib
	make -C flutiolib

.PHONY: clean
clean:
	make -C unixsocket clean
	make -C taglib clean
	make -C flutiolib clean

.PHONY: install
install:
	make -C unixsocket install
	make -C taglib install
	make -C flutiolib install

