input_libsndfile.o: input_libsndfile.c ../include/flutio/plugins/input.h \
 ../include/flutio/plugins/common.h \
 ../include/flutio/interfaces/framegen.h
output_alsa.o: output_alsa.c ../include/flutio/plugins/output.h \
 ../include/flutio/plugins/common.h
post_input_channelconvert.o: post_input_channelconvert.c
post_input_rateconvert.o: post_input_rateconvert.c
pre_output_softvolume.o: pre_output_softvolume.c
