#ifndef FLUTIO_PLUGINS_COMMON_H
#define FLUTIO_PLUGINS_COMMON_H

#define FLUTIO_PLUGIN_TYPE_INPUT       0
#define FLUTIO_PLUGIN_TYPE_POST_INPUT  1
#define FLUTIO_PLUGIN_TYPE_PRE_OUTPUT  2
#define FLUTIO_PLUGIN_TYPE_OUTPUT      3
#define FLUTIO_PLUGIN_TYPE_MSG_FORMAT  4
#define FLUTIO_PLUGIN_TYPE_FADE_EFFECT 5

typedef void* PluginData_T;

#endif // FLUTIO_PLUGINS_COMMON_H
